### ISSUE TITLE
Release as standalone plugin

### ISSUE THREAD

**Issue by sergeevabc** [navossoc/KeePass-Yet-Another-Favicon-Downloader#1]
Dear Rafael,
Could you be so kind to release your plugin in a proper form for end-users, i.e.```*.plgx```?

**Comment by navossoc** [comment]
Sure, I have plans to release it...

I took a break from the project, but I plan to resume it on the next week.

At the moment there is no advantage in using the plugin, since it lacks a crucial part of the implementation (that would be to search for the favicon in html page, I got it hardcoded it as a /favicon.ico file)

I'll let you know about any news. ;)

**Comment by navossoc** [comment]
@sergeevabc I've pushed some commits today, now the plugin can be considered a bit more usable.

In my internal tests, I have downloaded +6000 favicons in less than 15 minutes (of a 10000 total).
It still, it needs more work to be stable, accurate and fast.

For now, I'll analyze some results in more depth to see if the website really don't have a favicon or I'm missing something.
I already found some errors and a few places that needs improvement.

Soon I'll see how to pack a .plgx file and release the first version.

[]'s

**Comment by navossoc** [comment]
Hey @sergeevabc and @photonometric
Sorry for the wait, but the the time has finally come 👍.
Depending on how things go, the next updates will be much faster.

You can check the main page of this repository to get more information about the plugin itself and where to get it.

I did some additional tests and It should work on lower requirements, but it may need some fixes.
Please let me know what you guys think about it and any feedback is welcome.

Thanks.

**Comment by sergeevabc** [comment]
Dear Rafael, is some kind of error report planned (to see how many records and why were failed to get favicon)?

**Comment by navossoc** [comment]
@sergeevabc 
Well, you can see how many have succeeded or failed in the status bar, but that definitely is not a detailed report.

For sure, what you suggested can be an improvement. I think I can look at into later.
Any suggestions on how this report will be presented back to the user?

Besides that, are you using the plugin and have any feedback at all?

**Comment by sergeevabc** [comment]
> you can see how many have succeeded or failed in the status bar

Oh, Rafael, I missed that notice after the first launch.
Perhaps status label should be extended to “Favicons report:  ...”, and verbosity could be added later.

> Besides that, are you using the plugin?

Yes, as a lower footprint alternative to [Favicon Downloader][1] with a nice context menu icon.
Installation is usual, i.e. put ```..plgx``` into ```/Plugins``` and restart Keepass. Environment is Windows 7 x64.

[1]: https://sourceforge.net/projects/keepass-favicon/

**Comment by navossoc** [comment]
Sure, that can be easily done.
I need to see how to create a TODO list or something like that here on GitHub.

Anyhow, I think I'll close this issue now, since the plugin is already released.
