### ISSUE TITLE
Incompatibility with KeePass 2.35

### ISSUE THREAD

**Issue by kblais** [navossoc/KeePass-Yet-Another-Favicon-Downloader#10]
Hi,

I just tried installing the plugin on my KeePass, and here is the message I got on startup :

> The following plugin is incompatible with the current KeePass Version: /usr/lib/keepass2/Plugins/YetAnotherFaviconDownloader.plgz
> Have a look at the plugin's website for an appropriate version.

Are there any plans to make it work on this version ?

I use Debian Stretch with Mono 4.6.2, and KeePass 2.35 obviously.

Thanks :)

**Comment by navossoc** [comment]
I did a quick test here...

```shell
apt-get install keepass2
apt-get install mono-devel
sudo mv ~/Downloads/YetAnotherFaviconDownloader.plgx /usr/lib/keepass2/Plugins/
```

Then:
```shell
ls -la /usr/lib/keepass2/Plugins/
```

Outputs:
```shell
navossoc@debian:~$ ls -la /usr/lib/keepass2/Plugins/
total 24
drwxr-xr-x 2 root     root      4096 Dec 13 12:13 .
drwxr-xr-x 3 root     root      4096 Dec 13 12:03 ..
-rw-r--r-- 1 navossoc navossoc 15021 Dec 13 12:08 YetAnotherFaviconDownloader.plgx
```

Do you have `mono-devel` installed? It is a requirement for KeePass plugins.

Let me know.

**Comment by kblais** [comment]
Oops, forgot to answer 😕 

It worked fine, `mono-devel` was missing on my system. Thanks a lot :)
