### ISSUE TITLE
Error Log

### ISSUE THREAD

**Issue by ffes** [navossoc/KeePass-Yet-Another-Favicon-Downloader#11]
I have several sites (https://gitlab.com/ffes is one of them) that increase the error counter when I try to download the favicon. But there is no log file for the normal user. Looking at the code I see that `Utils.Log()` only does something in a DEBUG build.

What would be the easiest way to find out what went wrong while trying to download the favicon from those sites?

**Comment by ffes** [comment]
Never mind. Should looked first....

A dup of #2

**Comment by navossoc** [comment]
Yeah, sorry about that, but the only way right now to see the error messages is compiling/running the plugin on debug mode.
