### ISSUE TITLE
Not working at some sites

### ISSUE THREAD

**Issue by CrendKing** [navossoc/KeePass-Yet-Another-Favicon-Downloader#12]
Most of the time this plugin works. However, it fails to get favicon from some websites. For example, it hangs on www.bestbuy.com for long time before reporting "Error". During the hang, the cancel button does not interrupt the wait. www.hertz.com does not work with the same symptom. And if I load the page with Firefox, I can clearly see the `<rel type="icon">` or `<rel type="short icon">` nodes.

Some other sites fail with their login subdomain, but succeeds with the "www" domain. For example, reg.usps.com fails, but www.usps.com is OK. Further, https://www.amazon.com/ap/signin fails, but https://www.amazon.com/ is OK.

**Comment by navossoc** [comment]
Yes, to be honest some of this things are on my TODO list...

Including this one:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/2

I should have finished this already, but unfortunately those last few days are very busy.

Some of this errors are not just "can't find the favicon", maybe a failed TLS handshake with the server or something like that. .NET enforces some kind of security rules.
That is why the log will be useful and it it should be done already.

Besides that, the cancel action works between downloads, it is not async with each download per self. 
What I mean is if you have 10 downloads total and 4 of them are running, you can cancel the other 6 immediately.
This is a limitation on how I write the code, but can be improved later.

I was targeting a lower .NET version (C# 2.0) so it can be mono/linux compatible, but[ mono has others bugs](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/9) that prevent its operation on some cases anyway.
So I'm not sure if that was a good decision at the time.

Now that I have a small user base (3k downloads, yay!), including some linux users, it may be easier now to develop and test all that.

**Comment by photonometric** [comment]
Glad more people are noticing this plugin and you feel your efforts are appreciated, You do good work on this ^^

**Comment by navossoc** [comment]
@jokupudip Sure!

Can you please create an issue with more details about your environment? 
Thinks like: Windows/Linux? KeePass version, URL you are using, etc...

**Comment by alexanderadam** [comment]
I'm having the same problems on Linux with Keepass 2.36. Some entries work flawlessly but most of them are resulting in errors.
Is there anything I can do to help debugging?

PS: Thank you for this _awesome _plugin_. I love it!

**Comment by ag346** [comment]
I haven't had any luck downloading any icons. Using Keepass 2.39.1 portable on Windows 10. It simply says error, but not sure where to check error log. Perhaps the issue has something to do with security software, windows firewall, anti-malware?

**Comment by navossoc** [comment]
@ag346 can you try to install keepass? just to check if the problem is the "portable mode" or not.

**Comment by navossoc** [comment]
@ag346 I did some additional tests and it works properly on `portable mode`, maybe it is windows firewall blocking it.

---

I did a few improvements related to issues with TLS handshakes. Next version should solve most of them.
