### ISSUE TITLE
[Question] What are the differences between this plugin and the "orignal" favicon downloader?

### ISSUE THREAD

**Issue by soul4soul** [navossoc/KeePass-Yet-Another-Favicon-Downloader#15]
What are the differences between this plugin and the ["orignal" favicon downloader](https://sourceforge.net/projects/keepass-favicon/)?

**Comment by navossoc** [comment]
I think this may answer your question:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/4

**Comment by soul4soul** [comment]
I did read it. I guess I'm not too familiar with the original favicon downloader even thought I use it. On second read it seems most of the bullet points under "features" are the differences.

- Batch download
- Avoids duplicates icons
- Linux support
- Native Proxy

How does the avoid duplicate icons feature work? If I installed it now would it be able to retroactively clean up duplicate icons? What constitutes a duplicate icon? eg.perhaps a binary match

**Comment by navossoc** [comment]
> How does the avoid duplicate icons feature work? 

If one or more URLs points to the same favicon file, I can reuse the same icon and avoid store it twice on your password database.

> What constitutes a duplicate icon? eg.perhaps a binary match

Yes, it is a binary match.

Keep in mind that it works only for the icons downloaded by YAFD.

> If I installed it now would it be able to retroactively clean up duplicate icons?

No, it will not. There are no additional metadata for custom icons, so I can't keep track of where they came from and remove them.

If you want a really clean and tidy database, I suggest you remove all your custom icons and download them all again.

**Comment by soul4soul** [comment]
👌 Sounds good.
