### ISSUE TITLE
Download for all entries in all folders?

### ISSUE THREAD

**Issue by Tiwas** [navossoc/KeePass-Yet-Another-Favicon-Downloader#20]
Is it possible to download for every single entry in the database?

**Comment by navossoc** [comment]
The short answer is: right now no...

More info here:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/14

**Comment by Tiwas** [comment]
Thanks. Made a comment there. Will close this one. Thanks for extremely fast response!
