### ISSUE TITLE
Debian 9 + Mono 4.6.2 not work

### ISSUE THREAD

**Issue by MESWEB** [navossoc/KeePass-Yet-Another-Favicon-Downloader#22]
I try open KeePass 2.39.1 but I see error:

> The following plugin is incompatible with the current KeePass version:
> /usr/lib/keepass2/Plugins/YetAnotherFaviconDownloader.plgx

> Have a look at the plugin'swebsite for an appropriate version.

**Comment by navossoc** [comment]
Hi

I think you mean KeePass 2.39.1, right?

Mono now needs to be at least 4.8.0 as stated on the release page.
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.0.0

The latest Stable Mono release is: 5.14.0 Stable (5.14.0.177).
Debian package is too much outdated.

The instructions are on the page (really easy to follow):
https://www.mono-project.com/download/stable/#download-lin-debian

Make sure to also update your CA certificates.

There is an old issue with some additional information, you may want to look at it:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/9#issuecomment-348698644

**Comment by MESWEB** [comment]
@navossoc: Thank U for fix my problem. Just install mono-devel fix all.
