### ISSUE TITLE
YAFD force quits Keepass when trying to fetch favicons.

### ISSUE THREAD

**Issue by Swoy** [navossoc/KeePass-Yet-Another-Favicon-Downloader#24]
Hello, I'm facing a rather problematic issue:

## Steps to reproduce:
If I activate the option to use both `Automatic prefix URLs with http://`  and `Use title field if URL field is empty` in the order below: 

![20181104144920-](https://user-images.githubusercontent.com/5272077/47964951-e20f9180-e040-11e8-8f4f-33a68aacdb4a.png)

![20181104142648-](https://user-images.githubusercontent.com/5272077/47964686-c5258f00-e03d-11e8-9fd8-6d9791f1ebb7.png)

I then mark all items in a specific group (notice the visible columns):

![20181104145054-d__passmap kdbx - keepass](https://user-images.githubusercontent.com/5272077/47964999-80035c00-e041-11e8-899e-2c134a9ee7ba.png)

and select the option to download:

![20181104145327-](https://user-images.githubusercontent.com/5272077/47965005-93162c00-e041-11e8-8a86-17cf76ee5540.png)
 
## Result:
Keepass will suddenly behave as if the entire list is deleted, then the app quit unexpectedly. Luckily, I didn't make any changes to the database during this run, but any unsaved changes is confirmed to be lost if these repro-steps are preformed on an unsaved db.

I'm using it with the following plugins on KeePass 2.40:

| plugin | Version |
|:---|:---:|
| KeeChallenge | [1.5.0.0](http://richardbenjaminrush.com/keechallenge/) | 
| QuickConnectPlugin | [0.4.4.0](https://github.com/cristianst85/QuickConnectPlugin/releases) |
| ExeIconPicker | [1.0.2.0](https://github.com/eveldee0680/KeePass-ExeIconPicker/releases) |
|  HIBPOflineCheck | [1.3.1.0](https://github.com/mihaifm/HIBPOfflineCheck/releases) |
| KeeAnywhere | [1.5.1.0](https://github.com/Kyrodan/KeeAnywhere/releases) |
| KeePassHttp | [1.8.4.2](https://github.com/pfn/keepasshttp/releases) |
| KeeTrayTOTP | [0.9.5.0](https://github.com/victor-rds/KeeTrayTOTP/releases) |
| PasswordChangeAssistant | [1.1.0.0](https://sourceforge.net/projects/passwordchangeassistant/files/) |
| QualityColumn | [1.2.0.0](https://keepass.info/plugins.html#qcol) |
| QuickConnectPlugin | [0.4.4.0](https://github.com/cristianst85/QuickConnectPlugin/releases) |
| **YetAnother Favicon Downloader** | **1.2.0.0** |

**Comment by navossoc** [comment]
Hi, thanks for your report.

Can you please tell me more information about your system?

Also to make my life easier, if possible:

1. Have you tried to reproduce the same steps without the other plugins loaded?

2. Is it happening with another group of entries? (different sites or maybe just a subset of that selection)

This will help me to narrow down the issue.

[]'s

**Comment by navossoc** [comment]
To be honest, I already tried a few scenarios here.
So far I had no luck to reproduce it.

All I can think about is some of your password entries (title or url field) have any kind of special character or something like that.

Just to make sure: the crash happens only if you enable both options at the same time?

Another tests can be:

1. no options at all
2. just `automatic prefix` 
3. just `use title if url is empty`
4. prefix + title (you already did, crashed)

By the way, have you tried to select just two random entries and see what happens?
Are you being able to see the form dialog downloading the icons before it crashes?

[]'s

**Comment by Swoy** [comment]
I've looked further into the issue.
I've also managed to crash KeePass without those settings enabled now. 

The issue is not stable, but I've boiled down a few bits; and somehow, it makes it easier to crash KeePass if the following things are among the entries tried:

![20181105150448-e__database kdbx - keepass](https://user-images.githubusercontent.com/5272077/48003080-b1495e00-e10d-11e8-8345-d94e7ec1d5a1.png)

- Two entries with identical URLs (in URL field)
- KeePassHttp Settings entry
- an entry with `dropbox://` protocol in URL field
- an entry with normal string in title field and `http://something` in URL field.

Sometimes I get an exception window:
![20181105151144-e__passmap kdbx_ - keepass](https://user-images.githubusercontent.com/5272077/48002975-67f90e80-e10d-11e8-8347-e4b8286c71f4.png)

When your extension is doing it's job it also looks like there could be some optimization of when it repaints the list _(maybe this can be part of the culprit?)_ As you can see, I've captured a screen of when it crashes and the repaint fails:

![20181105151210-e__passmap kdbx_ - keepass](https://user-images.githubusercontent.com/5272077/48003071-ad1d4080-e10d-11e8-83e6-ea658fe00a04.png)

It seems that the extension fails to handle some issues correctly either when repainting or when it receives some unknown error during fetching.

**Comment by navossoc** [comment]
Nice...

This makes sense:
> Two entries with identical URLs (in URL field)

Probably a race condition trying to save the same icon.

I'll look further later tonight.

**Comment by Swoy** [comment]
Yes, it seems like part of the culprit. It also doesn't manage to repaint the list properly and duplicates _(only in view, not in db) all entries after **two entries with identical URLs in URL field** _(dupe URL)_ is in the job.

![20181105153056-e__passmap kdbx_ - keepass](https://user-images.githubusercontent.com/5272077/48003972-3b92c180-e110-11e8-90cd-b4f8b94addac.png)

**I also noticed the following**:
It seems that when you do this over an entry where KeeTrayTOTP is storing data and has it displayed in it's own column, it also crashes (unrelated to the dupe URL issue. When I disable the column, I won't crash anymore on anything else than dupe URL issue.
> It took me a few tries to get this screenshot, but I hope what is there could shed some light. unfortunately, it is impossible (for me at least) to scroll in that list before the window is destroyed.

![20181105152429-yet another favicon downloader](https://user-images.githubusercontent.com/5272077/48003997-464d5680-e110-11e8-8bc9-f3b71e8d998d.png)

**Comment by navossoc** [comment]
Great, this should be enough information for now.
I let you know if I discover something too...

Looking at the stack is something like you said: refreshing the list.
Probably this in an TOTP plugin issue, but I'll look it anyway.

I believe any refresh on the entry list may trigger this crash.

I don't recall any plugin that refresh the list right now, just this one:
https://github.com/luckyrat/KeePass-Favicon-Downloader

If you want to give it a try too, feel free...

[]'s

**Comment by Swoy** [comment]
Great! Here's hope we get to the bottom of this. The TOTP can refresh cells that should display TOTP's from what I can see. 

Nah, I like this extension better ❤️

**Comment by navossoc** [comment]
Well... well... well...

I did a few more tests:
KeePass + KeeTrayTOTP = no issues, with or without the plugin column.
KeePass + HIBPOfflineCheck = no issues, with or without the plugin column.
KeePass + KeeTrayTOTP + HIBPOfflineCheck = crash while the download is running (columns show).

I suspect that TOTP refreshes the list and HIBPOfflineCheck also.

From [HIBPOfflineCheck](https://github.com/mihaifm/HIBPOfflineCheck#usage) page:

> Entries are checked automatically after being updated


The call stack you posted on the image is different from the call stack of event log.
One is triggered by TOTP plugin and the other one is trigged by HIBP plugin.

Both plugins has some kinda of refresh feature:

https://github.com/mihaifm/HIBPOfflineCheck/blob/02bf23a8a6c5f4c88b7e5390476e354a0ad5249e/HIBPOfflineCheckExt.cs#L303

https://github.com/victor-rds/KeeTrayTOTP/blob/a6a431b7e5f8db21bcac6037205687f5b77b827b/TrayTOTP_Plugin.cs#L544

I didn't refresh the list while the download is running.
My code waits all the job is done, then it refreshes it only once.

https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/blob/55d8c059ad781a9fd6028c4ab8692fdcf6b2fb8d/YAFD/FaviconDialog.cs#L257

**Comment by Swoy** [comment]
##### Indeed, `TOTP` is the culprit. and boy do it present a performance hit too. It updates every second to display the count down for each `TOTP` in there, no matter if it is visible or hidden ****.  😠 
I will write up an issue over there for this and a few other things.

I've made a test DB with 2000 entries to test stability and the like (password is `123`):

[Database.zip](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/files/2550533/Database.zip)

When using this and downloading favicons for all 2000 entries, I experienced no issue whatsoever. The list update after was buttersmooth as well.

#### I am so sorry btw:
I also noticed a rookie mistake I did, I forgot to clear the plugin cache. After clearing it, and disabling TOTP _(and all the other plugins)_ your plugin worked with no issues so far. This seems to have been why, as for some reason TOTP was still working in the back? I have no idea as to why. But I apologize for the time I stole from you.

One last thing, does your plugin consider multiple of the same domain?? On that DB I attached, would it maybe complete quicker if you first ran a check for similar domains and group them as one during prep? Since there are ~400 unique domains, and that corresponds with the number of icons found in the `Use custom icon` menu.

**Comment by Swoy** [comment]
Thanks for looking into this anyway!

> KeePass itself already has a good drop in performance if you have too many entries, especially if you have the sort / grouping features enabled.

I haven't experienced any performance issues what-so-ever, I do however get application hang errors when I try to import csv's larger than 20MB (I haven't tried 10MB etc.). But I digress;

> HIBPOfflineCheck has an event that is triggered every time an entry is touched (updated).
During my tests, he was primarily responsible for crashing the program while the list of icons was being updated.

It seems that `HIBPOfflineCheck` indeed causes havoc during your plugins update. I simply disabled it since I only use it once in a while. While `KeeTrayTOTP` is in development I suppose he will look into these issues on his side as well - considering how useful his plugin is to many people.

**Comment by navossoc** [comment]
> I haven't experienced any performance issues what-so-ever.

Try to put all the entries on the same group or use the option `view -> show entries of subgroups`.
It will hang for a while, specialty if sort and group is enabled.

Anyway...

**Comment by navossoc** [comment]
@Swoy not sure if you get luck with the other plugins, but I did a small change that may help in cases like this.
