### ISSUE TITLE
Context menu hotkey

### ISSUE THREAD

**Issue by JohnLGalt** [navossoc/KeePass-Yet-Another-Favicon-Downloader#28]
Hi,  I love your alternate favicon DL plugin - it works really well on my database, and I'm using it to replace all the icons for my myriad of PWs in my database.

To make this a bit easier, I'd like to put in a RFF for allowing the plugin to claim the context menu hotkey of F (from _F_avicon) in order to make the process of updating favicons of a lot of entries a lot easier.

**Comment by navossoc** [comment]
You mean this?

![image](https://user-images.githubusercontent.com/2457338/54824594-287d2a00-4c8a-11e9-9cd8-872b30551a95.png)

**Comment by navossoc** [comment]
Added F for the single entry context menu and V for the group context menu.

**Comment by JohnLGalt** [comment]
That was exactly what I was looking for, thanks!
