### ISSUE TITLE
Downloading Icons for already downloaded sites?

### ISSUE THREAD

**Issue by NicciZar** [navossoc/KeePass-Yet-Another-Favicon-Downloader#34]
Hello,

Does this addon download icons for websites where I already have icons for?
Imagine refreshing your whole database.. does this try to download every icon or just the ones where no icon is placed?

What about icon that I placed with another addon from an exe for example? I dont want it to replace them.

**Comment by navossoc** [comment]
It will download only the icons you asks for.

If you choose you root group and then click on "Download Favicons" it will download everything, even it already have an icon.

If you want more control, you need to narrow down the group or download for a single entry only.

There is two gifs illustrating this behavior on the README.md, check it out...
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/blob/master/README.md

**Comment by NicciZar** [comment]
Thank you for your answer :)
That was just what I wanted to know.
