### ISSUE TITLE
This plugin changes Last Modification Time even for entries which it does not modify

### ISSUE THREAD

**Issue by NeatNit** [navossoc/KeePass-Yet-Another-Favicon-Downloader#35]
Title says it all.

Reproduction:
1. Create or find an entry with no URL (or which would otherwise fail to provide a favicon)
2. Right-click -> Download Favicons
3. YAFD reports "Error" (or "Not Found"), and the entry will not be modified but the entry's Last Modification Time will be updated to the current time.

Expected behavior: the Last Modification Time should not be updated whenever the icon is not updated, i.e. in any of the following situations:
* Could not find a URL
* The website has no favicon
* The website has a favicon, but it hasn't changed since the last time this plugin was used (compare the newly downloaded icon with the existing icon)

**Comment by navossoc** [comment]
> Title says it all.

It says all and a little bit more. 🤣 

Anyway, that is a good point.

**Comment by NeatNit** [comment]
Seems to work fine in a basic check, thanks! That was awesomely quick!

**Comment by navossoc** [comment]
@NeatNit it will always download the favicon.
Then it will determine if it has been changed hashing the data of the icon.

So, if you download a icon today and in the next month you download the same exactly file it will produce the same hash and will not be changed the icon on the entry (with this changes you proposed).

It also uses the same hash to share a custom icon between multiple entries, avoiding cluttering the database with many resources.

**Comment by JohnLGalt** [comment]
Very nice implementation! Thanks!

**Comment by navossoc** [comment]
So @NeatNit, did you find any problems?
I think it is good to go public.

**Comment by NeatNit** [comment]
Honestly I didn't use it at all after that comment, I don't have much more to do with it :P

But in my short testing back then it was fine. So yeah, go ahead.
