### ISSUE TITLE
Linux Mono 4.8.0: error downloading any icons

### ISSUE THREAD

**Issue by ftobin** [navossoc/KeePass-Yet-Another-Favicon-Downloader#36]
Trying to download favicons for any site fails in the `Error` category.

YAFD: 1.2.3.0
Mono JIT compiler version 4.8.0
Keepass 2.43
Gentoo Linux

**Comment by navossoc** [comment]
I'll try to install a gentoo on a VM later.

Are you root certificates updated?

There are some additional information here:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/wiki/Linux-install

To be honest I need to check if 4.8.0 still is a good fit with all this removal/deprecation around SSLv3/TLS1.0,TLS1.1.

**Comment by ftobin** [comment]
I did need to update root certificates, but that hasn't resolved the issue.  Strangely, my database seems to be when I run the plugin downloader (keepass allows me to save the database), but it still puts up a pop-up box saying error, and there are no favicons.

As a test of my root certificates, I run:
```csharp -e 'new System.Net.WebClient ().DownloadString ("https://www.google.com/")'```

Just as a note, I updated my certs by running:
```cert-sync --user /etc/ssl/certs/ca-certificates.crt```

**Comment by ciro73** [comment]
same here but update to the latest mono release (Mono JIT compiler version 6.8.0.105) like suggested here https://www.mono-project.com/download/stable solved that issue.

Mono JIT compiler version **6.8.0.105**
YAFD: 1.2.3.0
Keepass 2.44
Ubuntu (bionic) Linux

**Comment by navossoc** [comment]
@ftobin any luck? @ciro73 suggestion is basically what I was planning to do.

Sorry didn't look it yet, but last time I tried to play with Gentoo wasn't a pleasant experience 🤣 .

Which Gentoo image are you using?
Did you install mono and keepass from the Gentoo packages?

Let me know.

**Comment by ciro73** [comment]
@ftobin I'm using Ubuntu ;-)
Not very familiar with gentoo

**Comment by ftobin** [comment]
Gentoo's unmasked mono version is currently at 4.8.0.524: https://packages.gentoo.org/packages/dev-lang/mono

I'll try unmasking a more version tonight and see what happens.  Keepass is the only thing on my system that relies on mono.

Gentoo doesn't work with "images" -- it's a rolling release system.

**Comment by ftobin** [comment]
It was easiest to upgrade to mono 5.16.0.220 (less other dependencies needing upgrading).  YAFD works fine on Gentoo on that version.
