### ISSUE TITLE
download FavIco failed

### ISSUE THREAD

**Issue by zen010101** [navossoc/KeePass-Yet-Another-Favicon-Downloader#37]
https://pixabay.com/

the plugin download this website FavIco failed . Maybe it contains many icons .

**Comment by JohnLGalt** [comment]
Confirmed.  Also, looking at the page source, I found these items:

```
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
```

I verified that those are the actual favicons that are loaded by the site into the tab in Firefox.

**Comment by navossoc** [comment]
That is not the problem, the server is returning a 403 forbidden.

``` curl -I https://pixabay.com/```

Not sure why, probably against bots.

**Comment by zen010101** [comment]
maybe because of the UserAgent

**Comment by navossoc** [comment]
I have changed the UserAgent here to a newer version of Chrome and it didn't work too...

https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/blob/64b9f54f03d48ebed1b37fe6631ef53dcd9d1ab0/YAFD/FaviconDownloader.cs#L18

They offer a challenge that you will need to solve before enter the site.

[]'s

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
