### ISSUE TITLE
Not working with the latest KeePass

### ISSUE THREAD

**Issue by rootk1t** [navossoc/KeePass-Yet-Another-Favicon-Downloader#43]
Hello!

I'm using Keepass 2.44 with the Yet-Another-Favicon-Downloader v1.2.4.0.

After placing the file in plugins folder of the KeePass, an error during startup appears.
![error](https://user-images.githubusercontent.com/6153741/81315710-517d9b80-9093-11ea-9af0-a9ddc72a5ff6.jpg)

Is there a way to resolve this issue?

Thanks.

**Comment by navossoc** [comment]
Are you using Windows XP?

Not sure if .NET Framework 4.5 is available to Windows XP.

**Comment by rootk1t** [comment]
> Are you using Windows XP?
> 
> Not sure if .NET Framework 4.5 is available to Windows XP.

Yes. This seems to be the issue. The latest one for WinXP is .NET Framework 4 which is insufficient, i suppose. I didn't think at all, that KeePass plugins need .NET Framework to compile & work properly.

Thank you for clarification.

**Comment by navossoc** [comment]
No problem...

You may try an older version like v1.1.1.0.

I think it will run since it depends on .NET 2.0, but you will face issues with some sites because of new TLS protocols.

Sorry about that.

**Comment by rootk1t** [comment]
> 
> 
> No problem...
> 
> You may try an older version like v1.1.1.0.
> 
> I think it will run since it depends on .NET 2.0, but you will face issues with some sites because of new TLS protocols.
> 
> Sorry about that.

Thank you for recommending the right version for my case. v1.1.1.0 works as promised.
