### ISSUE TITLE
Unable to find favicon for seur.com

### ISSUE THREAD

**Issue by nolddor** [navossoc/KeePass-Yet-Another-Favicon-Downloader#44]
URL: https://www.seur.com/acceso-web-privada.do
![imagen](https://user-images.githubusercontent.com/1280022/83853076-08158000-a715-11ea-9e5f-0cbc2a350bea.png)

Plugin version:
![imagen](https://user-images.githubusercontent.com/1280022/83852944-d69cb480-a714-11ea-9441-f4979356963e.png)

**Comment by navossoc** [comment]
Incapsula is blocking the requests because its not a "real user".

```Request unsuccessful. Incapsula incident ID: 996014580056444955-119235430437907595```

![image](https://user-images.githubusercontent.com/2457338/83899407-cb568280-a72e-11ea-9733-fa3c704c0c58.png)

**Comment by nolddor** [comment]
Is there any way to fake the User-Agent o whatever is needed here to make it works?
Thanks!

**Comment by navossoc** [comment]
@nolddor 
We already do that, but they probably have some other rules to detect this kind of "bot".

**Comment by nolddor** [comment]
Probably the lack of JS support is the root cause of this block.

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
