### ISSUE TITLE
keepass 2.46 The icon will return to the default after saving

### ISSUE THREAD

**Issue by heibaigame** [navossoc/KeePass-Yet-Another-Favicon-Downloader#46]
<a href="https://sm.ms/image/lC5bZw49rXIGKeU" target="_blank"><img src="https://i.loli.net/2020/09/24/lC5bZw49rXIGKeU.gif" ></a>

**Comment by navossoc** [comment]
I see, it happens only to this entry (Origin) or any entry?

Not sure if this is an issue related to the language, but have you tried to change it to english for example?

Have you tried disabling other plugins?

Let me know.

**Comment by Osensei-GH** [comment]
@navossoc Solved, it is the problem of the "OnedriveSync" plug-in, just delete it

**Comment by navossoc** [comment]
Thanks for sharing.
