### ISSUE TITLE
Failed to retrieve icon for 3D Content Central

### ISSUE THREAD

**Issue by brunokc** [navossoc/KeePass-Yet-Another-Favicon-Downloader#49]
This one is weird. I can see an favicon for it at https://www.3dcontentcentral.com/favicon.ico but YAFD didn't detect it. I had to download it manually into KeePass.

**Comment by Hrxn** [comment]
Maybe related to #45?
HTTP/2 only?

**Comment by brunokc** [comment]
Indeed, it may be the same issue. Trying the request with curl using HTTP/1.1 and although it negotiates the TLS connection, it just stalls and eventually times out. :-\

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
