### ISSUE TITLE
Add http://

### ISSUE THREAD

**Issue by Qwash** [navossoc/KeePass-Yet-Another-Favicon-Downloader#5]
Almost all urls in my database added without "http://" or "https://" at the beggining
The plugin should be able to handle it _of course without any modification to the url entries in the database_

**Comment by navossoc** [comment]
Sure, I have thought about it when I was writing the plugin.

Do you think it is best to try https:// first, then http://?

Since we are moving to a "HTTPS" period, this maybe make more sense.

Just out of curiosity, why do you enter URLs without a schema?
Anyway, let me know.

**Comment by ZIEXED** [comment]
HTTPS won't bring any advantages since we are just fetching some icons
I think going for HTTP directly is better:)

_I don't really remember the reason :D_

**Comment by Qwash** [comment]
HTTPS won't bring any advantages since we are just fetching some icons
I think going for HTTP directly is better :)

_I don't really remember the reason :D_

**Comment by navossoc** [comment]
Well, I'll take a look on this weekend.

**Comment by navossoc** [comment]
Hey @Qwash , check this out...

https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.1.0.0-pre

This should do the trick for now, right?
Let me know and I will release it as the next update.

Thanks.

**Comment by Qwash** [comment]
I get "not found" whenever I try
I don't even see any DNS requests

**Comment by navossoc** [comment]
Ops, you almost got me 😨 for a second.

I will give a few days, then release it as the main version.

Let me know if you find any issue.

Thanks!

**Comment by navossoc** [comment]
Hey @Qwash, I have promoted that pre-release to a release.

Technically it's the same file. The only modification I did on the code was increment the version.
I hope this way, it will notify other users to update.

**Comment by Qwash** [comment]
OK, thank you 👍

**Comment by matthewmcpartland** [comment]
The current implementation adds http:// to all entries. I feel it would be better to simply handle urls with or without this portion added on to them

**Comment by navossoc** [comment]
@matthewmcpartland have you tested the option yet?

I mean, maybe I am not understanding exactly what are you talking about or I did not make myself very clear about how it works.

It "adds" the prefix http:// on the fly (on memory online).
It will **not** change your password entry on the database.

For example, you have a entry with a URL saved like this:
`github.com`

It will turn it in:
`http://github.com`

This process is done only in memory, the password entry will not be affected.
After you perform the "download favicons" action, the URL you have saved in your KeePass database will remain exactly the same.

Is this what you are referring to or did I misunderstand?

About the https, I'll look into too...

**Comment by matthewmcpartland** [comment]
I thought the option would edit all of the URLs in the database. With the option enabled it works beautifully.

Since I had though it would change the url, then it would be better to have the url be changed to https://. That said since it only loads it into memory I agree you should keep it as just http for legacy support.

Excellent work on this plugin btw, it really picks up where the other one left off

**Comment by navossoc** [comment]
@matthewmcpartland No, it won't edit anything else besides the custom icon on the password entry.

> Excellent work on this plugin btw, it really picks up where the other one left off

That was the plan 👍 

I'll change the wiki later to make this behavior more clear.
