### ISSUE TITLE
Quizlet DOT com

### ISSUE THREAD

**Issue by JohnLGalt** [navossoc/KeePass-Yet-Another-Favicon-Downloader#50]
Opening site shows a favicon in browser tab.  YAFD doesn't see it.   Looking at page source and searching for 'favicon' I found it readily enough - just weirdly named, is all.

"https://assets.quizlet.com/a/j/dist/i/favicon.6e263725c926227.ico"

Just thought you'd want to know.

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

**Comment by JohnLGalt** [comment]
Something similar for Pizza Hut DOT com:

"https://www.pizzahut.com/assets/ng/images/branding/phase-1/Website-Desktop-FaviconWhite-192x192.png"

**Comment by JohnLGalt** [comment]
And BestBuy DOT com:

"https://pisces.bbystatic.com/image2/BestBuy_US/Gallery/favicon-32-72227.png"

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
