### ISSUE TITLE
TechSoup DOT org

### ISSUE THREAD

**Issue by JohnLGalt** [navossoc/KeePass-Yet-Another-Favicon-Downloader#51]
YAFD doesn't find it, but searching page source finds it readily enough:

"https://www.techsoup.org/_layouts/15/TechSoup/ui/images/favicon.png"

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
