### ISSUE TITLE
Neverware Zendesk site

### ISSUE THREAD

**Issue by JohnLGalt** [navossoc/KeePass-Yet-Another-Favicon-Downloader#52]
Neverware (now owned by Google) has a ZenDesk site for FAQs and questions about their Neverware CloudReady Chrome OS for home, education and enterprise users.  URL:  https://neverware.zendesk.com/hc/en-us (English).  YAFD cannot find favicon seen in browser tab, but source search finds it:

"//theme.zdassets.com/theme_assets/187734/df7ad117882f0a0b8d3b4b06b43b09bb29ada9e3.png"

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
