### ISSUE TITLE
TireRack DOT com

### ISSUE THREAD

**Issue by JohnLGalt** [navossoc/KeePass-Yet-Another-Favicon-Downloader#53]
Browser tab shows a favicon, but I CANNOT find it in the source code.  I suspect it is loading via JS or some other manner.

Info:

Windows 10 20H2 (19042.804)
KeePass v2.47 x64
YAFD v1.2.4.0

**Comment by JohnLGalt** [comment]
Also, Sears DOT com

**Comment by navossoc** [comment]
Glad to see you are alive 👍 

Yeah, something need to be done.

I'll try to reserve some time to update this.

**Comment by JohnLGalt** [comment]
Lol.  I'm alive, for sure.  No rush, I just had a bit of time, so I updated
all my existing favicons and ran into a couple of issues.

I am sure I probably mentioned one or two of them before, but I was able to
download some again and manually add them in.  A couple though just
perplexed me.

Hope all is well with you during these crazy times with the pandemic.  Take
care and stay safe.

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
