### ISSUE TITLE
Icon not found for iTouchless.com

### ISSUE THREAD

**Issue by brogers5** [navossoc/KeePass-Yet-Another-Favicon-Downloader#57]
Entry URL: https://itouchless.com/account/login

Relevant code in the webpage:
```html
  <!-- Favicons
================================================== -->

  <link rel="shortcut icon" href="//cdn.shopify.com/s/files/1/0399/5942/9281/t/4/assets/favicon.png?v=15106769190101230059">
```

The icon is actually a WebP image, which KeePass does not natively support. When manually importing, I had to convert it to a PNG as a workaround.

**Comment by navossoc** [comment]
It can be downloaded now using a custom provider.
Release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
