### ISSUE TITLE
Custom Icons with Names >=KDBX 4.1 KeePass 2.48

### ISSUE THREAD

**Issue by 4-FLOSS-Free-Libre-Open-Source-Software** [navossoc/KeePass-Yet-Another-Favicon-Downloader#58]
With [KeePass 2.48](https://keepass.info/news/n210507_2.48.html) a [new database format version](https://keepass.info/help/kb/kdbx_4.1.html#ci) was introduced, that supports icon names.

It would be nice to have support for this.
I could think of using the domain name, the favicon was fetched from, for the icons name. ~~So that you can prevent duplicate redundancy icon storage in db for multiple entry or account of same domains. Or if you start favicon download, to fallback to lookup for existing icons that match `Name` to the domain part if `LastModificationTime` is not too old~~.

**Comment by JohnLGalt** [comment]
While I do like the naming convention, in my use, if you have multiple accounts on the same domain the icon for the same domain only gets downloaded once.  For example, I have several G-Suite accounts, and a few personal Google accounts as well - all the accounts downloaded the icon from 'google.com' but there is only a single entry for the icon in the custom icon database.

Same holds true with multiple Outlook.com accounts, NetZero accounts, and numerous other places where I have multiple accounts on the same domain.  I only get 1 copy of the icon and it gets re-used if it is called again.

**Comment by navossoc** [comment]
@4-FLOSS-Free-Libre-Open-Source-Software I don't think that will be necessary...

https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/issues/35

**Comment by navossoc** [comment]
Feature added on release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
