### ISSUE TITLE
Incompatibility with the current version of Keepass (2.48.1)

### ISSUE THREAD

**Issue by xaozai** [navossoc/KeePass-Yet-Another-Favicon-Downloader#59]
![Снимок экрана_2021-05-13_21-55-19](https://user-images.githubusercontent.com/8542452/118173457-455eb380-b436-11eb-8693-e1a89f7d19ec.png)

Could you please update the plugin.

**Comment by navossoc** [comment]
Not sure if the problem is on my end...

Can you report your KeePass and Mono version?

**Comment by xaozai** [comment]
The issue was resolved by updating mono-complete. Thanks!
