### ISSUE TITLE
Comparison with "Favicon Downloader"

### ISSUE THREAD

**Issue by Techman-** [navossoc/KeePass-Yet-Another-Favicon-Downloader#6]
What are the major pros/cons of this vs [Favicon Downloader](https://sourceforge.net/projects/keepass-favicon/)?

**Comment by navossoc** [comment]
Hello @Techman- I tried to summarize some of my changes here:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader#features

Maybe someone can share some feedback with you, but in the end there is no big difference between the plugins, it is just "yet another" plugin.
I have no plans for world domination or anything like that. 😆

**Comment by matthewmcpartland** [comment]
The other Favicon downloader can't handle a URL like http://accounts.google.com. It can handle urls without the http:// part which is nice.

This plugin requires http:// before your URL, explicitly not HTTPS. This plugin should prevent having multiple favicons that are exactly the same. Linux support and light weight I haven't really tested but those are obvious advantages. This plugin has active support from the dev.

**Comment by navossoc** [comment]
Hey @matthewmcpartland about the prefix, I made an option to change that, you can read more here:
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/wiki/Settings:-Automatic-prefix-URLs-with-HTTP

But it is disable by default, check it out and let me know.

**Comment by matthewmcpartland** [comment]
With that setting enabled, I really see no reason to use the other plugin. This one is much better for a lot of reasons

**Comment by Techman-** [comment]
I see, thanks.
