### ISSUE TITLE
Check if the file size for the favicon is too big

### ISSUE THREAD

**Issue by F-Wer** [navossoc/KeePass-Yet-Another-Favicon-Downloader#60]
I encountered a problem with Keepass2Android, because a downloaded favicon was too huge too handle it.

Therefore a check if the file size is realistic would be nice.

An example for a website where the downloaded favicon is huge is https://anchor.fm/.

The downloaded favicon is 11760x11760 pixel big and has a filesize of 846kb.

**Comment by navossoc** [comment]
This issue still exists?
Can you provide the link of this favicon?

I didn't find any oversized icon.
We can set a limit...

Which will be a reasonable size? 200kb?

[]'s

**Comment by F-Wer** [comment]
Yes this issue still exists. 

I only found one example and it's anchor.fm 
![Export](https://user-images.githubusercontent.com/43503689/136014670-3518fade-c48a-40df-a29b-ad734c72c43d.png)
This icon has a size of 933kb and all my other icons have a maximal size of 10kb.

**Comment by navossoc** [comment]
What is the URL where this icon is located?

I just found https://d12xoj7p9moygp.cloudfront.net/favicon/favicon-wave-32x32.png

**Comment by navossoc** [comment]
> Short question: Is there a part in the KeePass interface for a plugin to access the entirety of the custom icons stored in a KDBX? So that it's possible to enumerate/iterate over every icon?

Sure, [KeePass Custom Icon Dashboarder](https://github.com/incognito1234/KeePass-Custom-Icon-Dashboarder) kinda does that...
You should check it out too...

[]'s

**Comment by navossoc** [comment]
@F-Wer a sneaky peak ;)

![2021-10-08_00-40-32](https://user-images.githubusercontent.com/2457338/136494541-4a4d2573-a87a-4d91-ac21-237422ad0332.gif)

**Comment by navossoc** [comment]
Feature added on release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
