### ISSUE TITLE
[Feature] Auto-name icons

### ISSUE THREAD

**Issue by Mrfiregem** [navossoc/KeePass-Yet-Another-Favicon-Downloader#61]
Keepass now lets users name icons. It'd be pretty helpful for the icons downloaded here to be given the name of whatever the entry's `Title` is, for ease of searching. I'm not sure if it's possible for extensions to do this, however.

**Comment by navossoc** [comment]
Feature added on release [v1.2.5.0](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.2.5.0).
