### ISSUE TITLE
Latest Release Missing .plgx file?

### ISSUE THREAD

**Issue by adamdehaven** [navossoc/KeePass-Yet-Another-Favicon-Downloader#8]
I downloaded the latest release, but unless I'm missing something, it doesn't contain the `YetAnotherFaviconDownloader.plgx` file.

Am I looking in the wrong place, or did something change?

**Comment by navossoc** [comment]
Hi...

For the time being, the latest release is the v1.1.1.0.
https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader/releases/tag/v1.1.1.0

For me it's showing the plgx file.

![image](https://user-images.githubusercontent.com/2457338/32661642-d7b2342e-c60e-11e7-9a3a-dfb39093091f.png)

Where are you looking for the file?

**Comment by adamdehaven** [comment]
@navossoc thanks for the quick response... I'm stupid and was only looking at the .zip file, so didn't notice the totally obvious download link. Thanks! Love the plugin

**Comment by navossoc** [comment]
No problem, sometimes it happens to the best of us.

I was kind sleepy yesterday, so I had to check too.
No harm has been done 😆
